### ISSUE TITLE
Error using filtfilt. Expected input to be finite.

### ISSUE THREAD

**Issue by hehaodele** [pdechazal/Hypoxic-Burden#1]
Hello,

I encountered an error while running the calcHB.m script. The error messages are as follows:

```
Error using filtfilt
Expected input to be finite.

Error in filtfilt>efiltfilt (line 123)
    validateattributes(x,{'double','single'},{'finite','nonempty'},'filtfilt');

Error in filtfilt (line 102)
        y = efiltfilt(b,a,x);

Error in calcHB (line 146)
    SpO2avgfilt=filtfilt(B,1,SpO2avg);

Error in HBexample (line 2)
HB=calcHB(SpO2,RespEvents,SleepStage,true)
```

Upon investigation, I found that there are NaN values in SpO2avg. Is this expected behavior, or could it be causing the issue?

Thank you for your assistance!

**Comment by pdechazal** [comment]
Hi there


I suspect line 113 of calcHB.m causes issues as this code was developed with version 2017 matlab.

    SpO2avg=nanmean(SpO2event,2);


SpO2avg should contain no nans

Try replacing it with
SpO2avg=mean(SpO2event,2,’omitnan’)


Hope this helps

Philip

From: Hao He ***@***.***>
Sent: Friday, August 23, 2024 11:20 AM
To: pdechazal/Hypoxic-Burden ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pdechazal/Hypoxic-Burden] Error using filtfilt. Expected input to be finite. (Issue #1)


Hello,

I encountered an error while running the calcHB.m script. The error messages are as follows:

Error using filtfilt

Expected input to be finite.



Error in filtfilt>efiltfilt (line 123)

    validateattributes(x,{'double','single'},{'finite','nonempty'},'filtfilt');



Error in filtfilt (line 102)

        y = efiltfilt(b,a,x);



Error in calcHB (line 146)

    SpO2avgfilt=filtfilt(B,1,SpO2avg);



Error in HBexample (line 2)

HB=calcHB(SpO2,RespEvents,SleepStage,true)

Upon investigation, I found that there are NaN values in SpO2avg. Is this expected behavior, or could it be causing the issue?

Thank you for your assistance!

**Comment by hehaodele** [comment]
Awesome! Thank you for the prompt reply. Error caused by `nanmean` is solved. 

I believe the `nanmax` and `nansum` functions in line 231 should also be revised. Could you please let me know the correct way to do this?

**Comment by pdechazal** [comment]
Try:

Old: nansum( max(nanmax(SpO2phys(Finish-100*SpO2.SR:Finish))-SpO2phys(max(Finish+WinStart,Limit):Finish+WinFinish),0) )/(60*SpO2.SR); %percent minutes

New: sum( max(max(SpO2phys(Finish-100*SpO2.SR:Finish),’omitnan’)-SpO2phys(max(Finish+WinStart,Limit):Finish+WinFinish),0) ,’omitnan’)/(60*SpO2.SR); %percent minutes


Alternatively install the statistics toolbox and the nanmean, nanmax, nansum will work!

Good luck

Philip

**Comment by hehaodele** [comment]
Thanks for the suggestion. I tried and encountered an error.

```
Error using  - 
Arrays have incompatible sizes for this operation.

Error in calcHB (line 231)
            PercentMinsDesat=PercentMinsDesat +  sum( max(max(SpO2phys(Finish-100*SpO2.SR:Finish),'omitnan')-SpO2phys(max(Finish+WinStart,Limit):Finish+WinFinish),0) ,'omitnan')/(60*SpO2.SR); %percent minutes

Error in HBexample (line 2)
HB=calcHB(SpO2,RespEvents,SleepStage,true)
```

**Comment by hehaodele** [comment]
install the `statistics toolbox` solved my issue. Thank you so much for the help!
